[package]
name = "pdb-handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.78"
js-sys = "0.3.45"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
pdbtbx = "0.10.2"
console_error_panic_hook = { version = "0.1.7", optional = true }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
